export const  FETCH_SUBJECT_REQUEST ="FETCH_SUBJECT_REQUEST";
export const  FETCH_SUBJECT_SUCCESS ="FETCH_SUBJECT_SUCCESS";
export const  FETCH_SUBJECT_FAILURE ="FETCH_SUBJECT_FAILURE";

export const  FETCH_CHAPTER_REQUEST ="FETCH_CHAPTER_REQUEST";
export const  FETCH_CHAPTER_SUCCESS ="FETCH_CHAPTER_SUCCESS";
export const  FETCH_CHAPTER_FAILURE ="FETCH_CHAPTER_FAILURE";



